#!/bin/bash

# Directory containing the video files
VIDEO_DIR="$HOME/Videos/Wallpapers/"

# File containing ASCII art
LOGO_FILE="$HOME/.Projects/bash/live-wallpaper-project/logo"

# Function to display the logo
display_logo() {
  cat "$LOGO_FILE"
}

# Function to choose a live wallpaper
choose_wallpaper() {
  echo "Choose a live wallpaper:"
  select FILE_NAME in *.mp4 "Kill Background Wallpaper" "Exit"; do
    case "$FILE_NAME" in
      "Exit")
        echo "Exiting..."
        exit 0
        ;;
      "Kill Background Wallpaper")
        echo "Stopping Background Live Wallpaper"
        killall xwinwrap 2>/dev/null
        ;;
      *)
        selected_wallpaper="$FILE_NAME"
        break
        ;;
    esac
  done
}

# Function to launch xwinwrap with mpv
launch_xwinwrap() {
  killall xwinwrap 2>/dev/null
  nohup xwinwrap -g 1920x1080+0+0 -ovr -ni -- mpv --fullscreen --no-stop-screensaver --loop --no-audio --no-border --no-osc --no-osd-bar --no-input-default-bindings -wid WID "$selected_wallpaper" > /dev/null 2>&1 &
  printf "\ec"
}

# Signal handler to catch SIGINT and exit cleanly
trap 'echo "Killing Live Wallpaper And Exiting..."; exit 0' SIGINT

# Main function
main() {
  cd "$VIDEO_DIR" || { echo "Error: Unable to change directory to $VIDEO_DIR"; exit 1; }
  while true; do
    display_logo
    choose_wallpaper
    launch_xwinwrap
  done
}

main


